stages:
  - build
  - test

build:
  image: gradle:7.4.2-jdk8
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar

test:
  image: gradle:7.4.2-jdk8
  stage: test
  script:
    - gradle test